# Supplemental config for registry.redhat.io/ubi9/httpd-24 (port 8080 is default in image).
<Directory "/var/www/html">
  AllowOverride None
  Require all granted
</Directory>
<Directory "/var/www/html/rbd">
  Require all granted
</Directory>
<Directory "/var/www/html/cephfs">
  Require all granted
</Directory>
