# ODF RBD StorageClass for application workloads (filesystem PVC for httpd + writer).
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: regional-dr-test-rbd
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-ceph-rbd
